### ISSUE TITLE
Add onChange listener to editor

### ISSUE THREAD

**Issue by ponyr1der** [gravity-ui/markdown-editor#402]
### Description
The editor does not inform me in any way about changes in the content inside it. I need this to implement autosave whenever the content changes.

### Proposal
Add onChange listener to useMarkdownEditor or MarkdownEditorView that will return current value of the editor

**Comment by shevnv** [comment]
Editor instance, which you get from `useMarkdownEditor`, emit 'change' event and you can subscribe.

How this code might look like
```
export function Editor({onChange, text = ''}) {
    const editor = useMarkdownEditor({
       ... 
    });

    // Example of subscription to change event,
    // full list of available events is here https://github.com/gravity-ui/markdown-editor/blob/988df7cf98c68cad0687518f82bca88e45038268/src/bundle/Editor.ts#L35
    React.useEffect(() => {
        const onChangeHandler = () => {
            onChange(editor.getValue());
        };

        editor.on('change', onChangeHandler);

        return () => {
            editor.off('change', onChangeHandler);
        };
    }, [editor, onChange]);

    return (
        <MarkdownEditorView
            ...
        />
    );
}
```

@ponyr1der, Is this what you wanted?

**Comment by ponyr1der** [comment]
Yeah, that's it! Thanks a lot.
