### ISSUE TITLE
Add sideEffects for tree shaking

### ISSUE THREAD

**Issue by makhnatkin** [gravity-ui/markdown-editor#521]
### Description
When you import a component for rendering <Html/>, it pulls in the entire editor package, which is over 1 MB in size.

### Proposal
I suggest using tree shaking

https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffects
https://github.com/gravity-ui/uikit/blob/main/package.json#L84

**Comment by u4aew** [comment]
Do we need to remove Gulp and use Webpack with tree shaking support, or should we use Gulp together with Webpack?
